version: '3.8'
services:

  application:
    build: ./
    container_name: patient-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/patient
      - DB_USER=postgres
      - DB_PASS=admin
    volumes:
      - ./target:/app
    command: java -jar /app/patient-service-docker.jar

  postgres:
    container_name: patient-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: patient
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 5s
      retries: 3

  pgadmin:
      container_name: patient-pgadmin
      image: dpage/pgadmin4:latest
      restart: always
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
        - "5050:80"
      depends_on:
        - postgres